Implement version validation for server, client, and contenders
Each server/client module should define SERVER_MIN_REV and/or CLIENT_MIN_REV (or
specify any undefined variable(s) in inherit_default_init), and each contender
module should do similarly for CONTENDER_MIN_REV.

The server and client minimun revisions, if specified, will be treated as Git
revisions of the SERVER_DIR and CLIENT_DIR directories, respectively, and any
commit descended from that one will be accepted.  The default behavior of both
variables is to ignore the revision (i.e. skip the version check altogether).

This validation behavior can be customized (e.g. to call a program with its
--version flag or similar) by overriding the check{server,client,contender}rev
functions.  These are special "internal" functions that do *not* need to be
specified in inherit_default_init regardless of whether a module defines them.

Note that there is no default logic for checking contender revisions, so any
module that wishes to have its program validated *must* implement its own
checkcontenderrev function; otherwise, a warning will be printed and any and all
contender version checks will report failure.

diff --git a/network_rtt b/network_rtt
--- a/network_rtt
+++ b/network_rtt
@@ -149,6 +149,24 @@ then
 	exit 3
 fi
 
+checkrevision() {
+	component="$1"
+	errorcode="$2"
+
+	whichrev="\"$`echo "$component" | tr [a-z] [A-Z]`_MIN_REV\""
+	whichchk="\"check${component}rev\""
+
+	if eval [ -n "$whichrev" ] && ! eval "$whichchk"
+	then
+		eval printf "\"ERROR: Component '$component' is older than minimum supported version ('%s')!\n\"" "$whichrev" >&2
+		exit "$errorcode"
+	fi
+}
+
+checkrevision server 4
+checkrevision client 5
+checkrevision contender 6
+
 if [ -z "$logfilename" ]
 then
 	cat >&2 <<-tac
