network_rtt: Check remote Git revision and working tree changes
This does not, however, ensure that the remote build is up to date.

diff --git a/network_rtt b/network_rtt
--- a/network_rtt
+++ b/network_rtt
@@ -18,6 +18,21 @@ then
 	exit 1
 fi
 
+localrev="`git log --no-abbrev-commit -1 | head -n1 | cut -d' ' -f2`"
+remoterev="`ssh "$foreign_client" "cd '$remote_path'; git log --no-abbrev-commit -1 | head -n1 | cut -d' ' -f2"`"
+if [ "$localrev" != "$remoterev" ]
+then
+	echo "ERROR: Version mismatch between systems!" >&2
+	exit 2
+fi
+
+remotemod="`ssh "$foreign_client" "cd '$remote_path'; git diff --exit-code HEAD >/dev/null; echo \\$?"`"
+if [ "$remotemod" -ne 0 ]
+then
+	echo "ERROR: Remote repository state uncommitted!" >&2
+	exit 3
+fi
+
 jaguar/jaguar set "$logfilename" legend.samples.table_entries.description string "Number of pointers to chase through"
 jaguar/jaguar set "$logfilename" legend.samples.table_entries.unit string ""
 jaguar/jaguar set "$logfilename" legend.samples.round_trip_time.description string "Round trip time from client perspective"
