Add EXPECTS_FILES variable for checking prerequisites are present to networked experiment module system
By default, this confirms that the server and contenders are built before allowing an experiment to start.

diff --git a/network_rtt b/network_rtt
--- a/network_rtt
+++ b/network_rtt
@@ -173,6 +173,15 @@ then
 	exit 7
 fi
 
+eval printf '"%s\n"' $EXPECTS_FILES | while read prereqfile
+do
+	if [ ! -e "$prereqfile" ]
+	then
+		echo "ERROR: Required file '$prereqfile' couldn't be found!" >&2
+		exit 8
+	fi
+done || exit $?
+
 if [ -z "$logfilename" ]
 then
 	cat >&2 <<-tac
