clients/summarize_square_evictions: Build the target program at the start
This prevents the silent failure case of generating a log full of "command not found"s.

diff --git a/clients/summarize_square_evictions b/clients/summarize_square_evictions
--- a/clients/summarize_square_evictions
+++ b/clients/summarize_square_evictions
@@ -27,6 +27,13 @@ fi
 logfile="$1"
 mask="$2"
 tool="$3"
+
+if ! make square_evictions
+then
+	echo "Failed to build target utility!"
+	exit 1
+fi
+
 exec >"$logfile" 2>&1
 runlog git log --oneline -1
 runlog git status -uno
